version: "3.7"

services:
  app_proxy:
   environment:
     APP_HOST: jade-pinserver_web_1
     APP_PORT: $APP_PINSERVER_WEB_PORT

  node:
    image: tulipan81/blind_pin_server:v0.0.3@sha256:b251bac87b5a3b302769554bd19baded30e1a89b844f88872b70d09ff1717451
    depends_on:
      - tor
      - web
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - $APP_PINSERVER_PORT:$APP_PINSERVER_PORT
    volumes:
      - ${APP_DATA_DIR}/data/server_public_key.pub:/server_public_key.pub
      - ${APP_DATA_DIR}/data/server_private_key.key:/server_private_key.key
      - ${APP_DATA_DIR}/data/pins:/pins

  web: 
    image: tulipan81/pinserver_web:v0.0.30@sha256:80a576b16869c007bda5f903f0d0f7f0c837f7a86fe216decf50075286e62e67
    depends_on: 
      - tor
    restart: on-failure
    ports:
      - $APP_PINSERVER_WEB_PORT:$APP_PINSERVER_WEB_PORT
    volumes:
      - ${APP_DATA_DIR}/data/server_public_key.pub:/app/server_public_key.pub
      - ${APP_DATA_DIR}/data/server_private_key.key:/app/server_private_key.key
      - ${APP_DATA_DIR}/data/pins:/app/pins
    environment:
      PINSERVER_URL_A: ${APP_PINSERVER_HIDDEN_SERVICE}
      PINSERVER_PORT_A: ${APP_PINSERVER_PORT}
      PINSERVER_URL_B: ${APP_TAILSCALE_URL}
      PINSERVER_PORT_B: ${APP_PINSERVER_PORT}

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"
